project:
  type: website

website:
  title: "Qblog Demo"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/maithgopalan
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

